name: magnet
channels:
  - defaults
dependencies:
  - python=3.12
  - pip:
    - accelerate==1.5.2
    - einops==0.8.1
    - gdown==5.2.0
    - h5py==3.13.0
    - jaxtyping==0.3.0
    - loguru==0.7.3
    - numpy==2.2.4
    - scipy==1.15.2
    - tqdm==4.67.1
    - typing-extensions==4.12.2
    - tyro==0.9.17
    - viser==0.2.23
    - wandb==0.19.8
    - omegaconf==2.3.0
    - tensorboardx==2.6.4
    - scikit-learn==1.8.0
